### ISSUE TITLE
Broken for 1.0

### ISSUE THREAD

**Issue by hayden9002** [blockout22/ItemSpawner#1]
The mod is broken for 1.0. Please fix it.

**Comment by blockout22** [comment]
It's not broken I haven't updated it yet.

Join discord if you want to be notified when it's updated 

https://discord.gg/ds696q4

**Comment by Ahmadre** [comment]
> It's not broken I haven't updated it yet.
> 
> Join discord if you want to be notified when it's updated
> 
> https://discord.gg/ds696q4

Your discord link is not working...
